### PR TITLE
Throw RangeError if dateStyle/timeStyle is attempted with required equals to the other.

### PR DESCRIPTION
**Pull request by zbraniecki**
Fixes the remaining piece of #35.

### CODE REVIEW

**Comment by zbraniecki** [comment]
@littledan, @anba - does it look good to you?

**Comment by zbraniecki** [comment]
Depending on the resolution of #46 I may shift it to `TypeError` prior or after landing.

**Comment by anba** [comment]
The possible values for `required` and `defaults` are:

- InitializeDateTimeFormat
    - required: any
    - defaults: date
- toLocaleString
    - required: any
    - required: all
- toLocaleDateString
    - required: date
    - required: date
- toLocaleTimeString
    - required: time
    - required: time

And we only want to throw for:
- `toLocaleDateString` and `timeStyle` is present.
- `toLocaleTimeString` and `dateStyle` is present.

So I think the error conditions should be:

- If required is "date" and timeStyle is not undefined, throw a Range/TypeError exception.
- If required is "time" and dateStyle is not undefined, throw a Range/TypeError exception.

**Comment by zbraniecki** [comment]
Ah, right! We don't want to throw on `required = "any"`. I updated the patch.

@anba can you take another look for r?

**Comment by anba** [comment]
LGTM!

Can you add the two new steps below the existing two `Get` calls for `date/timeStyle`, instead of moving all steps before `If required is "date" or "any", then`? That way the `Get` calls in `ToDateTimeOptions` for the individual properties will be executed in the same order as in `InitializeDateTimeFormat`.

**Pull request merged**
