### PR TITLE
Normative: Honor hourCycle with dateStyle/timeStyle

### PR DESCRIPTION
**Pull request by littledan**
Fixes #11

### CODE REVIEW

**Comment by littledan** [comment]
cc @jungshik @FrankYFTang @zbraniecki

**Comment by FrankYFTang** [comment]
LGTM

**Comment by zbraniecki** [comment]
LGTM! Thank you Dan!

**Comment by littledan** [comment]
Thanks for all the reviews. I'll merge this now, and we can review in the next Intl meeting.

**Pull request merged**
